version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: ttc-db
    restart: always
    environment:
      POSTGRES_PASSWORD: #Set root password
      POSTGRES_DB: ClubCash
      POSTGRES_USER: dev
    volumes:
      # Change volume to store the data
      - /volume1/docker/ttccashregister/postgres:/var/lib/postgresql/data
    networks:
      - clubcash-backend

    #Use this if you need direct acces to docker database container for debugging purposes
    #ports:
      # - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d ClubCash"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 5

  webapp:
    container_name: ttc-web
    image: clubcashregister:latest
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      USERMAP_UID: 1029
      USERMAP_GID: 100
      UI_APPNAME: ClubCash
      UI_HOMEDESCRIPTION: Administrationtool for club treasures
      UI_APPNAMENAVBAR: ClubCash
      Logging__LogLevel__Default: "Debug"
      Logging__LogLevel__Microsoft.EntityFrameworkCore: "Information"
      ASPNETCORE_ENVIRONMENT: "Production"
      DbPassword: #Secret POSTGRES_PASSWORD:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@admin.de
      ADMIN_PASSWORD: #another secret pw for first user

    volumes:

      - /volume1/docker/ttccashregister/Exports:/app/exports
      - /volume1/docker/ttccashregister/logs:/app/logs
    networks:
      - clubcash-backend
      - proxy

networks:
  clubcash-backend:
    driver: bridge
  proxy:
    external: true
