// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCCashRegister.Data;

#nullable disable

namespace TTCCashRegister.Migrations
{
    [DbContext(typeof(CashDataContext))]
    [Migration("20241011074936_FirstInit")]
    partial class FirstInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TTCCashRegister.Data.Models.CashRegister", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("ID");

                    b.ToTable("CashRegister");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CostUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostUnitDetailsID")
                        .HasColumnType("int");

                    b.Property<string>("CostUnitName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CostUnitDetailsID");

                    b.ToTable("CostUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CostUnitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CostUnitsDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountMovement")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CashRegisterID")
                        .HasColumnType("int");

                    b.Property<int>("CostUnitID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Documentnumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CashRegisterID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CostUnit", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Models.CostUnitDetails", "CostUnitDetails")
                        .WithMany()
                        .HasForeignKey("CostUnitDetailsID");

                    b.Navigation("CostUnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.Transaction", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Models.CashRegister", "CashRegister")
                        .WithMany("Transactions")
                        .HasForeignKey("CashRegisterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegister");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CashRegister", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
