// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCCashRegister.Data;

#nullable disable

namespace TTCCashRegister.Migrations
{
    [DbContext(typeof(CashDataContext))]
    [Migration("20241019192041_ImplementBasicUnitForMoreDetails")]
    partial class ImplementBasicUnitForMoreDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TTCCashRegister.Data.Models.BasicUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CostUnitId");

                    b.ToTable("BasicUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CashRegister", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CostUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CostUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.SpecialItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Betrag")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SpecialItems");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountMovement")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BasicUnitID")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterID")
                        .HasColumnType("int");

                    b.Property<int>("CostUnitID")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Documentnumber")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialItemID")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UnitDetailsD")
                        .HasColumnType("int");

                    b.Property<int>("UnitDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicUnitID");

                    b.HasIndex("CashRegisterID");

                    b.HasIndex("CostUnitID");

                    b.HasIndex("SpecialItemID");

                    b.HasIndex("UnitDetailsD");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.UnitDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicUnitId")
                        .HasColumnType("int");

                    b.Property<string>("CostDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BasicUnitId");

                    b.ToTable("UnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.BasicUnit", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Models.CostUnit", "CostUnit")
                        .WithMany("BasicUnitDetails")
                        .HasForeignKey("CostUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CostUnit");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.Transaction", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Models.BasicUnit", "BasicUnit")
                        .WithMany()
                        .HasForeignKey("BasicUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.Models.CashRegister", "CashRegister")
                        .WithMany("Transactions")
                        .HasForeignKey("CashRegisterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.Models.CostUnit", "CostUnit")
                        .WithMany()
                        .HasForeignKey("CostUnitID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.Models.SpecialItem", "SpecialItem")
                        .WithMany()
                        .HasForeignKey("SpecialItemID");

                    b.HasOne("TTCCashRegister.Data.Models.UnitDetails", "UnitDetails")
                        .WithMany()
                        .HasForeignKey("UnitDetailsD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicUnit");

                    b.Navigation("CashRegister");

                    b.Navigation("CostUnit");

                    b.Navigation("SpecialItem");

                    b.Navigation("UnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.UnitDetails", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Models.BasicUnit", "BasicUnit")
                        .WithMany("CostUnitDetails")
                        .HasForeignKey("BasicUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BasicUnit");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.BasicUnit", b =>
                {
                    b.Navigation("CostUnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CashRegister", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Models.CostUnit", b =>
                {
                    b.Navigation("BasicUnitDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
