// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCCashRegister.Data;

#nullable disable

namespace TTCCashRegister.Migrations
{
    [DbContext(typeof(CashDataContext))]
    [Migration("20250225084401_SecondtryForManyToMany")]
    partial class SecondtryForManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BasicUnitModelUnitDetailsModel", b =>
                {
                    b.Property<int>("BasicUnitsId")
                        .HasColumnType("int");

                    b.Property<int>("CostUnitDetailsId")
                        .HasColumnType("int");

                    b.HasKey("BasicUnitsId", "CostUnitDetailsId");

                    b.HasIndex("CostUnitDetailsId");

                    b.ToTable("PositionDetails", (string)null);
                });

            modelBuilder.Entity("TTCCashRegister.Data.BasicUnit.BasicUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CostUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CostUnitId");

                    b.ToTable("BasicUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostUnit.CostUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CostUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SpecialItem.SpecialItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Betrag")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SpecialItems");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountMovement")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BasicUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<int>("CostUnitId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Documentnumber")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("UnitDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicUnitId");

                    b.HasIndex("CashRegisterId");

                    b.HasIndex("CostUnitId");

                    b.HasIndex("SpecialItemId");

                    b.HasIndex("UnitDetailsId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UnitDetails");
                });

            modelBuilder.Entity("BasicUnitModelUnitDetailsModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.BasicUnit.BasicUnitModel", null)
                        .WithMany()
                        .HasForeignKey("BasicUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", null)
                        .WithMany()
                        .HasForeignKey("CostUnitDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TTCCashRegister.Data.BasicUnit.BasicUnitModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.CostUnit.CostUnitModel", "CostUnit")
                        .WithMany("BasicUnitDetails")
                        .HasForeignKey("CostUnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CostUnit");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.BasicUnit.BasicUnitModel", "BasicUnit")
                        .WithMany()
                        .HasForeignKey("BasicUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CashRegister.CashRegisterModel", "CashRegister")
                        .WithMany("Transactions")
                        .HasForeignKey("CashRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CostUnit.CostUnitModel", "CostUnit")
                        .WithMany()
                        .HasForeignKey("CostUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.SpecialItem.SpecialItemModel", "SpecialItem")
                        .WithMany()
                        .HasForeignKey("SpecialItemId");

                    b.HasOne("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", "UnitDetails")
                        .WithMany()
                        .HasForeignKey("UnitDetailsId");

                    b.Navigation("BasicUnit");

                    b.Navigation("CashRegister");

                    b.Navigation("CostUnit");

                    b.Navigation("SpecialItem");

                    b.Navigation("UnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostUnit.CostUnitModel", b =>
                {
                    b.Navigation("BasicUnitDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
