// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCCashRegister.Data;

#nullable disable

namespace TTCCashRegister.Migrations
{
    [DbContext(typeof(CashDataContext))]
    [Migration("20250921131525_ChangeSubTransactionsToNotNullable")]
    partial class ChangeSubTransactionsToNotNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TTCCashRegister.Data.Accounts.AccountsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasicUnitId")
                        .HasColumnType("int");

                    b.Property<int>("CostUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("UnitDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BasicUnitId");

                    b.HasIndex("CostUnitId");

                    b.HasIndex("UnitDetailsId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("TTCCashRegister.Data.BasicUnit.BasicUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CostUnitId");

                    b.ToTable("BasicUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostUnit.CostUnitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CostUnits");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Person.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SpecialItem.SpecialItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpecialItems");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SubTransaction.SubTransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SubTransactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountMovement")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AccountsId")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Documentnumber")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountsId");

                    b.HasIndex("CashRegisterId");

                    b.HasIndex("Documentnumber")
                        .IsUnique();

                    b.HasIndex("SpecialItemId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Accounts.AccountsModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.BasicUnit.BasicUnitModel", "BasicUnit")
                        .WithMany("Accounts")
                        .HasForeignKey("BasicUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CostUnit.CostUnitModel", "CostUnit")
                        .WithMany("Accounts")
                        .HasForeignKey("CostUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", "UnitDetails")
                        .WithMany("Accounts")
                        .HasForeignKey("UnitDetailsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BasicUnit");

                    b.Navigation("CostUnit");

                    b.Navigation("UnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.BasicUnit.BasicUnitModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.CostUnit.CostUnitModel", "CostUnit")
                        .WithMany("BasicUnitDetails")
                        .HasForeignKey("CostUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostUnit");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SubTransaction.SubTransactionModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Person.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TTCCashRegister.Data.Transaction.TransactionModel", "Transaction")
                        .WithMany("SubTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Accounts.AccountsModel", "Accounts")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CashRegister.CashRegisterModel", "CashRegister")
                        .WithMany("Transactions")
                        .HasForeignKey("CashRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.SpecialItem.SpecialItemModel", "SpecialItem")
                        .WithMany("Transactions")
                        .HasForeignKey("SpecialItemId");

                    b.Navigation("Accounts");

                    b.Navigation("CashRegister");

                    b.Navigation("SpecialItem");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Accounts.AccountsModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.BasicUnit.BasicUnitModel", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostUnit.CostUnitModel", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("BasicUnitDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SpecialItem.SpecialItemModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.Navigation("SubTransactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.UnitDetail.UnitDetailsModel", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
