// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTCCashRegister.Data;

#nullable disable

namespace TTCCashRegister.Migrations
{
    [DbContext(typeof(CashDataContext))]
    [Migration("20250924091608_RefactorTransactionAndAllocationModel")]
    partial class RefactorTransactionAndAllocationModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TTCCashRegister.Data.Allocation.AllocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemDetailId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemDetailId");

                    b.HasIndex("CostCenterId", "CategoryId", "ItemDetailId")
                        .IsUnique();

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Category.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostCenterId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CostCenterId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostCenter.CostCenterModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CostCenters");
                });

            modelBuilder.Entity("TTCCashRegister.Data.ItemDetail.ItemDetailModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CostDetails")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ItemDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Person.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SpecialItem.SpecialItemModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SpecialItems");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccountMovement")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("AllocationId")
                        .HasColumnType("int");

                    b.Property<int>("CashRegisterId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int>("Documentnumber")
                        .HasColumnType("int");

                    b.Property<int?>("SpecialItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("AllocationId");

                    b.HasIndex("CashRegisterId");

                    b.HasIndex("Documentnumber")
                        .IsUnique();

                    b.HasIndex("SpecialItemId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.TransactionDetails.TransactionDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("DocumentNumber")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("Sum")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("TransactionId");

                    b.ToTable("TransactionDetails");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Allocation.AllocationModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Category.CategoryModel", "Category")
                        .WithMany("Allocations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CostCenter.CostCenterModel", "CostCenter")
                        .WithMany("Allocations")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.ItemDetail.ItemDetailModel", "ItemDetail")
                        .WithMany("Allocations")
                        .HasForeignKey("ItemDetailId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CostCenter");

                    b.Navigation("ItemDetail");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Category.CategoryModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.CostCenter.CostCenterModel", "CostCenter")
                        .WithMany("Categories")
                        .HasForeignKey("CostCenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CostCenter");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Allocation.AllocationModel", "Allocation")
                        .WithMany("Transactions")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.CashRegister.CashRegisterModel", "CashRegister")
                        .WithMany("Transactions")
                        .HasForeignKey("CashRegisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TTCCashRegister.Data.SpecialItem.SpecialItemModel", "SpecialItem")
                        .WithMany("Transactions")
                        .HasForeignKey("SpecialItemId");

                    b.Navigation("Allocation");

                    b.Navigation("CashRegister");

                    b.Navigation("SpecialItem");
                });

            modelBuilder.Entity("TTCCashRegister.Data.TransactionDetails.TransactionDetailsModel", b =>
                {
                    b.HasOne("TTCCashRegister.Data.Person.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TTCCashRegister.Data.Transaction.TransactionModel", "Transaction")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Allocation.AllocationModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CashRegister.CashRegisterModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Category.CategoryModel", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("TTCCashRegister.Data.CostCenter.CostCenterModel", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("TTCCashRegister.Data.ItemDetail.ItemDetailModel", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("TTCCashRegister.Data.SpecialItem.SpecialItemModel", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TTCCashRegister.Data.Transaction.TransactionModel", b =>
                {
                    b.Navigation("TransactionDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
